#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-Screen
version:      1.03
version_from: Screen.pm
installdirs:  site
requires:
    Term::Cap:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
